# Generated by Django 2.1.5 on 2020-10-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Sale'), ('N', 'New'), ('O', 'Out of Stock')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
