# Generated by Django 2.1.5 on 2020-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Home'), ('M', ''), ('A', 'Accessories'), ('T', 'Toys')], default=' ', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('N', 'New'), ('S', 'Sale')], max_length=1),
        ),
    ]
