# Generated by Django 2.1.5 on 2020-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201002_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Accessories'), ('T', 'Toys'), ('M', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Sale'), ('N', 'New'), ('O', 'Out of Stock')], max_length=1),
        ),
    ]
