# Generated by Django 2.1.5 on 2020-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201003_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='discounted',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Home Decor'), ('T', 'Toys'), ('M', ''), ('A', 'Accessories')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Sale'), ('O', 'Out of Stock')], max_length=1),
        ),
    ]
