# Generated by Django 2.1.5 on 2020-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201003_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', ''), ('H', 'Home Decor'), ('T', 'Toys'), ('A', 'Accessories')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('O', 'Out of Stock'), ('N', 'New'), ('S', 'Sale')], max_length=1),
        ),
    ]
