# Generated by Django 2.1.5 on 2020-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201003_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='inital_date',
            new_name='initial_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Accessories'), ('T', 'Toys'), ('H', 'Home Decor'), ('M', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.Order_Item'),
        ),
    ]
